name: Deploy UI to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'ui/**'
      - '.github/workflows/deploy-ui.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/genai-ui:latest ./ui
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/genai-ui:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: genai-ui-2025
          publish-profile: ${{ secrets.AZURE_UI_PUBLISH_PROFILE }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/genai-ui:latest